# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1crj5X2m34vxYgL-MWw5VhmsoqdbTJ_fm
"""

!pip install yfinance
!pip install PANDAS
!pip install numpy
!pip install pandas
!pip install statsmodels
!pip install arch

import numpy as np
from scipy.stats import norm, t # Import necessary distributions
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import acf # Needed for 'a' function
from statsmodels.graphics.tsaplots import plot_acf # Needed for 'a' function
from arch import arch_model
import bisect

Apple = "AAPL"
apple_ticker = yf.Ticker(Apple)
data = apple_ticker.history(period='1mo', auto_adjust=True)
close = data["Close"]
a = np.array(close)
#logged trasnfromed returns to get volatility
log_return = np.log(a[1:]/a[:-1])
print(log_return)
#Now to get historical volatility
Hist_vol = np.std(log_return)
len(a)

Microsoft = "MSFT"
msft_ticker = yf.Ticker(Microsoft)
msft_data = msft_ticker.history(period='1mo', auto_adjust=True)
msft_close = msft_data["Close"]
b=np.array(msft_close)
print(b)
print(a)

portfolio = []
portfolio.append(asset_1)
portfolio.append(asset_2)
price_matrix = np.vstack(portfolio)
print(price_matrix.shape)
def portfolio_vec(weight, price_matrix):
  percent=(price_matrix[:, 1:] - price_matrix[:, :-1]) / price_matrix[:, :-1]
  port_vec = np.dot(weight,price_matrix)
  percent_vec = np.dot(weight, percent)
  return percent,port_vec, percent_vec

def kurtosis(percent_vec):
  mean=np.mean(percent_vec)
  avg_fourth = np.mean((percent_vec-mean)**4)
  std = np.std(percent_vec)**4
  kurtosis = avg_fourth/std
  return kurtosis-3

def a(percent_vec):
  squared_values = percent_vec**2
  k = acf(squared_values, adjusted=False, nlags=18, qstat=True, fft=True, alpha=0.05, bartlett_confint=True, missing='none')
  plt.figure(figsize=(10,5))
  plot_acf(
      squared_values,
      lags=18,
      alpha=0.05
    )
  plt.show()

#def hist_risk(port_vec,alpha):
#  if len(port_vec) <100:
#    print(f"lack of data may lead to insufficient statistical reliability")
#  w = np.sort(port_vec)
#  q = int(np.floor(alpha*len(port_vec)))
#  VaR = abs(w[q])

#move onto expected shortfall completing our historical risk fucntion
#  E_SF = abs(np.mean(w[:q]))
#  print(f"The historical {alpha*100}% VaR for {len(port_vec)} days is: {VaR}")
#  print(f"The historical {alpha*100}% Expected shortfall for {len(port_vec)} days is: {E_SF}")
#  return VaR, E_SF

def hist_risk(percent_vec,alpha):
  if len(percent_vec) <100:
    print(f"lack of data may lead to insufficient statistical reliability")
  w = np.sort(percent_vec)
  q = int(np.floor(alpha*len(percent_vec)))
  VaR = abs(w[q])

#move onto expected shortfall completing our historical risk fucntion
  E_SF = abs(np.mean(w[:q]))
  print(f"The historical {alpha*100}% VaR for {len(percent_vec)} days is: {VaR}")
  print(f"The historical {alpha*100}% Expected shortfall for {len(percent_vec)} days is: {E_SF}")
  return VaR, E_SF

#Now using parametric following Daniellson book closely for foumale

#def normal_risk(value, alpha, weight, price_matrix):
#  #drift = np.mean(port_vec)
  #vol = np.sd(port_vec)
#  sd =  np.sqrt(weight.T@np.cov(price_matrix, rowvar=True)@ weight)
#  VaR = -sd*norm.ppf(alpha)*value

  #ES
#  ES= sd*norm.pdf(norm.ppf(alpha))/alpha *value

#  print(f"The normal {alpha*100}% VaR for {price_matrix.shape[1]} days is: {VaR}")
#  print(f"The normal {alpha*100}% Expected shortfall for {price_matrix.shape[1]} days is: {ES}")
#  return VaR, ES

def normal_riskp(value, alpha, weight, percent):
  #drift = np.mean(port_vec)
  #vol = np.sd(port_vec)
  sd =  np.sqrt(weight.T@np.cov(percent, rowvar=True)@ weight)
  VaR = -sd*norm.ppf(alpha)*value

  #ES
  ES= sd*norm.pdf(norm.ppf(alpha))/alpha *value

  print(f"The normal {alpha*100}% VaR for {percent.shape[1]} days is: {VaR}")
  print(f"The normal {alpha*100}% Expected shortfall for {percent.shape[1]} days is: {ES}")
  return VaR, ES

#def student_risk(value, alpha, weight, price_matrix, kurtosis):
#  DF = (6/kurtosis)+4
#  sd =  np.sqrt(weight.T@np.cov(price_matrix, rowvar=True)@ weight)
#  VaR = -sd*t.ppf(alpha,DF)*value

  #ES
#  ES = sd*(t.pdf(t.ppf(alpha,DF),DF)/alpha)*((DF+ t.ppf(alpha,DF)**2)/(DF-1))*value
#  print(f"The t dist {alpha*100}% VaR for {price_matrix.shape[1]} days is: {VaR}")
#  print(f"The t dist {alpha*100}% Expected shortfall for {price_matrix.shape[1]} days is: {ES}")
#  return VaR, ES

def student_risk(value, alpha, weight, percent, kurtosis):
  DF = (6/kurtosis)+4
  sd =  np.sqrt(weight.T@np.cov(percent, rowvar=True)@ weight)
  VaR = -sd*t.ppf(alpha,DF)*value

  #ES
  ES = sd*(t.pdf(t.ppf(alpha,DF),DF)/alpha)*((DF+ t.ppf(alpha,DF)**2)/(DF-1))*value
  print(f"The t dist {alpha*100}% VaR for {percent.shape[1]} days is: {VaR}")
  print(f"The t dist {alpha*100}% Expected shortfall for {percent.shape[1]} days is: {ES}")
  return VaR, ES

def EWMA(percent, weight, value, alpha):
  T = percent.shape[1]
  l = 0.94
  cov =  np.cov(percent, rowvar=True)
  for t in range(1,T):
    returns_at_t_minus_1 = percent[:, t-1].reshape(-1, 1) # Make it a column vector
    cov = l * cov + (1 - l) * (returns_at_t_minus_1 @ returns_at_t_minus_1.T)

  sigma = np.sqrt(weight.T@cov@weight)
  VaR = -sigma*norm.ppf(alpha)*value
  return VaR

def GARCH(percent_vec, weight, value, alpha):
  # Ensure percent_vec is a pandas Series for arch_model, if it's a numpy array, convert it.
  if not isinstance(percent_vec, pd.Series):
    percent_vec_series = pd.Series(percent_vec)
  else:
    percent_vec_series = percent_vec

  GARCH_model = arch_model(percent_vec_series,mean = 'constant', lags=0, vol = 'GARCH', p=1, q=1, o=0, power= 2.0, dist = 'normal', rescale = True)
  res = GARCH_model.fit(update_freq=5, disp="off")
  print(res.summary())

# 1. Extract the fitted parameters
  omega = res.params['omega']
  garch_alpha = res.params['alpha[1]'] # Renamed to avoid conflict with VaR alpha
  garch_beta = res.params['beta[1]']   # Renamed to avoid conflict with VaR alpha

# 2. Get the "Shock" (y_t)
# This is the return from the very last day in your dataset
  y_t = percent_vec_series.iloc[-1] # Use iloc for the Series

# 3. Get the "Memory" (h_t)
# The library stores the historical standard deviations.
# We grab the very last one and square it to get the variance.
  h_t = res.conditional_volatility.iloc[-1] ** 2

# 4. Compute tomorrow's variance (sigma^2_t+1)
# This is the exact mathematical formula from the textbook
  sigma2_forecast = omega + (garch_alpha * (y_t ** 2)) + (garch_beta * h_t)

# 5. Convert back to Standard Deviation for your VaR formula
  sigma_forecast = np.sqrt(sigma2_forecast)
  var = -sigma_forecast*norm.ppf(alpha)*value # Use the original 'alpha' argument for VaR
  return var

#https://iifx.dev/en/articles/456515453/adjusted-prices-in-yfinance-close-vs-adj-close-explained-with-code-samples

def backtesting(start,end, VaR,ES,ticker):
  #data = yf.download(ticker, start=start, end=end, auto_adjust=False)[['close']]
  dollar_changes_matrix = price_matrix[:, 1:] - price_matrix[:, :-1]
  count = sum(1 for x in data if x < -VaR)

  k=np.sort(data)
  l=bisect.bisect_left(k,-VaR)
  n=np.mean(k[:l]) if l>0 else np.nan
  actual_es = np.mean(k[:l]) if l > 0 else np.nan

    # 7. Calculate the severity of the shortfall
    if not np.isnan(actual_es):
        D_ES = (np.abs(actual_es) - ES) / ES
    else:
        D_ES = 0.0  # Safe fallback if there were zero breaches
  return count, D_ES

np.random.seed(42) # Lock the random generator

# Generate 105 days of RETURNS
asset_1_returns = np.random.normal(loc=0.0005, scale=0.01, size=105)
asset_2_returns = np.random.normal(loc=0.0010, scale=0.02, size=105)

# Matrix Assembly & Collapse
returns_matrix = np.vstack([asset_1_returns, asset_2_returns]) # This serves as the 'percent' or 'asset_returns_matrix' for risk functions
weights = np.array([0.5, 0.5])
percent_vec = np.dot(weights, returns_matrix) # This is the 1D portfolio returns vector

# Calculate kurtosis using the function defined above
kurtosis_value = kurtosis(percent_vec)

# ==========================================
# ZONE 4: EXECUTION
# ==========================================
portfolio_value = 1_000_000  # Testing a $1 Million Portfolio
alpha = 0.05 # Define alpha for clarity

print("\n--- $1,000,000 PORTFOLIO RISK REPORT ---")
print(f"Days of History: {len(percent_vec)}")
print(f"Excess Kurtosis: {kurtosis_value:.4f}\n") # Corrected function name to kurtosis

print("--- Historical Risk (Percentage VaR/ES) ---")
# hist_risk expects (percent_vec, alpha) and returns percentage VaR/ES.
# It also prints its own output.
hist_VaR_pct, hist_ES_pct = hist_risk(percent_vec, alpha)
# Manually print scaled dollar values for consistency with other risk models
print(f"Historical {alpha*100}% VaR (dollar value): {hist_VaR_pct * portfolio_value:.2f}")
print(f"Historical {alpha*100}% ES (dollar value): {hist_ES_pct * portfolio_value:.2f}\n")


print("--- Normal Risk (Dollar VaR/ES) ---")
# normal_riskp expects (value, alpha, weight, percent) where 'percent' is the returns_matrix.
normal_VaR, normal_ES = normal_riskp(portfolio_value, alpha, weights, returns_matrix)


print("\n--- Student-t Risk (Dollar VaR/ES) ---")
# student_risk expects (value, alpha, weight, percent, kurtosis) where 'percent' is the returns_matrix.
student_VaR, student_ES = student_risk(portfolio_value, alpha, weights, returns_matrix, kurtosis_value)


print("\n----------------------------------------")

a(percent_vec)